version: '2'
services:
  tests:
    build: .
    command: npm test
    environment:
      - WEB_HOST=web
  db:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build:
      context: ../api
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
  web:
    build: .
    ports:
      - "80:80"
    links:
      - "api"
    environment:
      - API_HOST=api:3000
